export const directoryCategories = [
  {
    label: "Profesionales",
    items: [
      "Abogado",
      "Administrador",
      "Arquitecto",
      "Contador",
      "Diseñador gráfico",
      "Diseñador UX/UI",
      "Ingeniero civil",
      "Ingeniero informático",
      "Ingeniero industrial",
      "Ingeniero químico",
      "Psicólogo",
      "Publicista",
      "Traductor",
    ],
  },
  {
    label: "Salud",
    items: [
      "Cardiólogo",
      "Clínico",
      "Dermatólogo",
      "Gastroenterólogo",
      "Ginecólogo",
      "Kinesiólogo",
      "Nutricionista",
      "Odontólogo",
      "Oftalmólogo",
      "Otorrino",
      "Pediatra",
      "Traumatólogo",
    ],
  },
  {
    label: "Tecnología",
    items: [
      "Analista de datos",
      "Desarrollador backend",
      "Desarrollador frontend",
      "Desarrollador móvil",
      "Especialista en ciberseguridad",
      "Especialista en IA",
      "Soporte técnico",
      "Tester QA",
    ],
  },
  {
    label: "Construcción y reformas",
    items: [
      "Albañil",
      "Arquitecto",
      "Colocación de durlock",
      "Carpintero",
      "Cerrajero",
      "Electricista",
      "Gasista",
      "Herrero",
      "Pintor",
      "Plomero",
      "Soldador",
      "Vidriero",
    ],
  },
  {
    label: "Hogar y servicios",
    items: [
      "Aire acondicionado",
      "Jardinero",
      "Limpieza",
      "Niñera",
      "Peluquería a domicilio",
      "Reparación de electrodomésticos",
      "Reparación de celulares",
      "Tapicero",
    ],
  },
  {
    label: "Automotor",
    items: ["Chapista", "Mecánico", "Electricista automotor"],
  },
];
