export const JUJUY_PROVINCE = "Jujuy";

export const JUJUY_LOCALITIES = [
  "Abra Pampa",
  "Aguas Calientes",
  "Caimancito",
  "Calilegua",
  "El Carmen",
  "El Piquete",
  "El Talar",
  "Fraile Pintado",
  "Humahuaca",
  "La Mendieta",
  "La Quiaca",
  "Libertador General San Martín",
  "Maimará",
  "Monterrico",
  "Palpalá",
  "Perico",
  "Puesto Viejo",
  "Purmamarca",
  "San Antonio",
  "San Pedro de Jujuy",
  "Santa Clara",
  "San Salvador de Jujuy",
  "Tilcara",
  "Yala",
  "Yuto",
];
